backend:
  name: github
  repo: "sauvagesalon/salonsauvage.be"
  branch: master


media_folder: "/media/"
public_folder: "media"


collections:

  - name: "pages"
    label: "Pages"
    label_singular: "page"
    folder: "_pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string" }
      - {label: "Url", name: "permalink", widget: "string" }
      - {label: "Layout", name: "layout", widget: "hidden", required: true, default: "page" }
      - {label: "Description", name: "description", widget: "text"}
      - label: "Banner"
        name: image
        required: false
        widget: object
        fields:
          - {label: "Image", name: "url", widget: "image", required: false }
          - {label: "Alt", name: "alt", widget: "string", required: false }
          - {label: "Caption", name: "caption", widget: "string", required: false }
      - {label: "Body", name: "body", widget: "markdown", required: false }
      - label: "Cards"
        name: aside
        required: false
        widget: list
        fields:
          - {label: "Title", name: "title", widget: "string", required: false }
          - label: "Image"
            name: image
            required: false
            widget: object
            fields:
              - {label: "Image", name: "url", widget: "image", required: false }
              - {label: "Alt", name: "alt", widget: "string", required: false }
          - {label: "Description", name: "description", widget: "markdown", required: false }
          - {label: "Url", name: "url", widget: "string", required: false }
      - label: "includes"
        name: includes
        required: false
        widget: list
        fields:
          - {label: "Type", name: "type", widget: "select", options: ["posts", "latest-posts", "form", "instagram", "map"], required: true }
          - {label: "Tag/Name", name: "data", widget: "string", required: false}

  - name: "posts"
    label: "Posts"
    label_singular: "post"
    folder: "_collections/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm", default: "YYYY-MM-DD hh:mm"}
      - {label: "Layout", name: "layout", widget: "hidden", required: true, default: "post" }
      - {label: "Description", name: "description", widget: "text"}
      - label: "Image"
        name: "image"
        required: false
        widget: object
        fields:
          - {label: "Image", name: "url", widget: "image", required: false }
          - {label: "Alt", name: "alt", widget: "string", required: false }
          - {label: "Caption", name: "caption", widget: "string", required: false }
      - label: "Banner"
        name: "banner"
        required: false
        widget: object
        fields:
          - {label: "Image", name: "url", widget: "image", required: false }
          - {label: "Alt", name: "alt", widget: "string", required: false }
          - {label: "Caption", name: "caption", widget: "string", required: false }
      - {label: "Body", name: "body", widget: "markdown", required: false }
      - {label: "Published", name: "published", widget: "boolean", default: true}

  - name: "forms"
    label: "Forms"
    label_singular: "form"
    editor:
      preview: false
    folder: "_collections/_forms"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false }
      - {label: "Success message", name: "success", widget: "text", required: "false"}
      - label: "Fields"
        name: fields
        widget: "list"
        fields:
          - {label: "Name", name: name, widget: string}
          - {label: "Label", name: label, widget: string}
          - {label: "Type", name: "type", widget: "select", options: ["text", "textarea", "email", "number", "file", "select", "submit"], default: "text" }
          - {label: "Required", name: "required", widget: "boolean", default: false}
          - {label: "Options", name: options, widget: "list", required: false}

  - name: "site"
    label: "Website"
    delete: false
    create: false
    editor:
      preview: false
    files:
      - name: "menu"
        label: "Menu"
        file: "_data/menu.yml"
        fields:
          - {label: "Title", name: "title", widget: "string" }
          - name: links
            label: Links
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - name: "url"
                label: "Url"
                required: false
                widget: relation
                collection: pages
                searchFields: [title, permalink]
                valueField: permalink
      - name: "info"
        label: "Info"
        file: "_data/info.yml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Street", name: "street", widget: "string", required: false }
          - {label: "Postal", name: "postal", widget: "string", required: false }
          - {label: "Locality", name: "locality", widget: "string", required: false }
          - {label: "Phone", name: "phone", widget: "string", required: false }
          - {label: "Mobile", name: "mobile", widget: "string", required: false }
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - label: "Opening Hours"
            name: "opening-hours"
            required: false
            widget: list
            fields:
              - {label: "Day", name: "day", widget: "string", required: false }
              - {label: "Time", name: "time", widget: "string", required: false }
              - {label: "Description", name: "description", widget: "markdown", required: false }
          - label: "Social"
            name: "social"
            required: false
            widget: list
            fields:
              - {label: "Platform", name: "platform", widget: "string", required: false }
              - {label: "Title", name: "title", widget: "string", required: false }
              - {label: "Profile", name: "profile", widget: "string", required: false }
              - {label: "Url", name: "url", widget: "string", required: false }
